# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nktmemo_ja
email: h.tanaka36@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    nktmemo provides interesting articles about Machine Learning and NLP.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nktmemoja.github.io" # the base hostname & protocol for your site
twitter_username: nkt_dev
github_username:  nkt1546789

# Build settings
markdown: kramdown
#highlighter: pygments